import { Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const oswald = Oswald({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // 👈 Add the weights you need
  variable: "--font-oswald",
  display: "swap", 
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={oswald.variable}> 
      <body className="min-h-full flex flex-col">
        <Navbar/>
        
        {children}
        
        
        </body>
    </html>
  );
}
